---
apiVersion: v1
kind: Pod
metadata:
  name: deleter
  namespace: heptio-sonobuoy
spec:
  containers:
  - env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: gcr.io/heptio-images/namespace-deleter:latest
    imagePullPolicy: Always
    name: deleter
  serviceAccountName: sonobuoy-serviceaccount
